### ISSUE TITLE
Error: Invalid or corrupt jarfile /verifier.jar

### ISSUE THREAD

**Issue by MemoryZy** [thepieterdc/intellij-plugin-verifier-action#15]
I received an error when running the command `java -jar /verifier.jar`.

![图片](https://github.com/thepieterdc/intellij-plugin-verifier-action/assets/64096987/cfb398ce-cc44-4783-85da-c4c27455740a)

![图片](https://github.com/thepieterdc/intellij-plugin-verifier-action/assets/64096987/5a300d85-1b0c-45d2-8533-befc0f9c271c)

<br/>

Here is my complete script.

``` yml
name: Compatibility Verification
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build the plugin using Gradle
      run: ./gradlew buildPlugin
    - uses: thepieterdc/intellij-plugin-verifier-action@1.3.0
      with:
        plugin: '/home/runner/work/demo-plugin/demo-plugin/build/distributions/demo-plugin-*'
        verifier_version: 1.365
        versions: |
          2022.3.3
          LATEST-EAP-SNAPSHOT
```
